baseURL = 'https://lik-uspeh.ru'
languageCode = 'ru'
title = 'Гимназия «ЛИК-Успех»'
defaultContentLanguage = 'ru'

# SEO и метаданные
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

# Настройки сборки
[build]
  writeStats = true

# Параметры темы
[params]
  description = "Частная гимназия «ЛИК-Успех» - качественное образование в Москве"
  keywords = ["гимназия", "частная школа", "образование", "Москва", "ЛИК-Успех"]
  author = "Гимназия «ЛИК-Успех»"
  email = "info@lik-uspeh.ru"
  phone = "+7 (495) XXX-XX-XX"
  address = "Москва, ул. Примерная, д. 1"
  
  # Социальные сети
  telegram = "https://t.me/lik_uspeh"
  vk = "https://vk.com/likuspeh"
  
  # Настройки блога
  blog_pagination = 6
  posts_per_page = 10

# Меню навигации - Концепция двухъярусной навигации
[menus]
  # Основное меню (6 пунктов для родителей)
  [[menus.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

  [[menus.main]]
    identifier = "about"
    name = "О школе"
    url = "/about/"
    weight = 2

  [[menus.main]]
    identifier = "admission"
    name = "Поступление"
    url = "/admission/"
    weight = 3

  [[menus.main]]
    identifier = "kindergarten"
    name = "Детский сад"
    url = "/kindergarten/"
    weight = 4

  [[menus.main]]
    identifier = "news"
    name = "Новости"
    url = "/news/"
    weight = 5
    hasChildren = true

  [[menus.main]]
    identifier = "contacts"
    name = "Контакты"
    url = "/contacts/"
    weight = 6

  # Подменю "Новости" (дроп-даун)
  [[menus.main]]
    identifier = "news-announcements"
    name = "Новости"
    url = "/news/"
    parent = "news"
    weight = 51

  [[menus.main]]
    identifier = "events"
    name = "События"
    url = "/events/"
    parent = "news"
    weight = 52

  [[menus.main]]
    identifier = "blog"
    name = "Блог"
    url = "/blog/"
    parent = "news"
    weight = 53

  # Utility-bar меню (верхняя полоса)
  [[menus.utility]]
    identifier = "organization"
    name = "Сведения об организации"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/"
    weight = 1

  [[menus.utility]]
    identifier = "diary"
    name = "Электронный дневник"
    url = "https://login.dnevnik.ru/"
    weight = 2
    external = true

  [[menus.utility]]
    identifier = "vacancies"
    name = "Вакансии"
    url = "/organization/vacancies/"
    weight = 3

# Подменю для "Сведения об организации" (side-nav)
  [[menus.organization]]
    identifier = "basic-info"
    name = "Основные сведения"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/osnovnye-svedeniya/"
    weight = 1

  [[menus.organization]]
    identifier = "structure"
    name = "Структура и органы управления"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/struktura-i-organy-upravleniya/"
    weight = 2

  [[menus.organization]]
    identifier = "documents"
    name = "Документы"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/dokumenty/"
    weight = 3

  [[menus.organization]]
    identifier = "education-info"
    name = "Образование"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/obrazovanie/"
    weight = 4

  [[menus.organization]]
    identifier = "standards"
    name = "Образовательные стандарты и требования"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/obrazovatelnye-standarty/"
    weight = 5

  [[menus.organization]]
    identifier = "staff"
    name = "Руководство. Педагогический состав"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/rukovodstvo-pedagogicheskiy-sostav/"
    weight = 6

  [[menus.organization]]
    identifier = "facilities"
    name = "Материально-техническое обеспечение"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/materialno-tekhnicheskoe-obespechenie/"
    weight = 7

  [[menus.organization]]
    identifier = "support"
    name = "Стипендии и меры поддержки обучающихся"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/stipendii-i-mery-podderzhki/"
    weight = 8

  [[menus.organization]]
    identifier = "paid-services"
    name = "Платные образовательные услуги"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/platnye-obrazovatelnye-uslugi/"
    weight = 9

  [[menus.organization]]
    identifier = "finance"
    name = "Финансово-хозяйственная деятельность"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/finansovo-khozyaystvennaya-deyatelnost/"
    weight = 10

  [[menus.organization]]
    identifier = "vacancies"
    name = "Вакантные места для приёма (перевода) обучающихся"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/vakantnye-mesta/"
    weight = 11

  [[menus.organization]]
    identifier = "accessibility"
    name = "Доступная среда"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/dostupnaya-sreda/"
    weight = 12

  [[menus.organization]]
    identifier = "international"
    name = "Международное сотрудничество"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/mezhdunarodnoe-sotrudnichestvo/"
    weight = 13

  # Футер меню - быстрые ссылки
  [[menus.footer_quick]]
    name = "О школе"
    url = "/about/"
    weight = 1

  [[menus.footer_quick]]
    name = "Поступление"
    url = "/admission/"
    weight = 2

  [[menus.footer_quick]]
    name = "Детский сад"
    url = "/kindergarten/"
    weight = 3

  [[menus.footer_quick]]
    name = "Новости"
    url = "/news/"
    weight = 4

  [[menus.footer_quick]]
    name = "Контакты"
    url = "/contacts/"
    weight = 5

  # Футер меню - юридическая информация
  [[menus.footer_legal]]
    name = "Сведения об организации"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/"
    weight = 1

  [[menus.footer_legal]]
    name = "Документы"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/dokumenty/"
    weight = 2

  [[menus.footer_legal]]
    name = "Финансовая отчётность"
    url = "/svedeniya-ob-obrazovatelnoy-organizatsii/finansovo-khozyaystvennaya-deyatelnost/"
    weight = 3

  [[menus.footer_legal]]
    name = "Противодействие коррупции"
    url = "/protivodeystvie-korruptsii/"
    weight = 4

# Настройки таксономий
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Настройки форматов вывода
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# Настройки RSS
[services.rss]
  limit = 20

# Настройки разметки
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Настройки обработки изображений
[imaging]
  resampleFilter = "lanczos"
  quality = 85
  anchor = "smart"
