name: Test Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Позволяет запускать workflow вручную
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        fi

    - name: Test Hugo build
      run: |
        echo "Testing Hugo build..."
        hugo --buildDrafts --destination public-test

    - name: Test Hugo build (production)
      run: |
        echo "Testing production build..."
        hugo --minify --destination public-prod
